version: '3.8'
services:
    mariadb:
        image: 'mariadb:10'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: prisma
        # volumes:
        #     - mysql:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p prisma"]
            retries: 3
            timeout: 5s
